### ISSUE TITLE
The `RSTUF_BOOTSTRAP_NODE` should be optional as mentioned in the documentation. 

### ISSUE THREAD

**Issue by juniorlpa** [repository-service-tuf/repository-service-tuf-api#163]
### Describe the bug

If the variable `RSTUF_BOOTSTRAP_NODE` is missing causes a fail during the run stage.

See erro below:

```shell
dev-repository-service-tuf-api-repository-service-tuf-api-1     | INFO:     Will watch for changes in these directories: ['/opt/repository-service-tuf-api']
dev-repository-service-tuf-api-repository-service-tuf-api-1     | INFO:     Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
dev-repository-service-tuf-api-repository-service-tuf-api-1     | INFO:     Started reloader process [1] using StatReload
dev-repository-service-tuf-api-repository-service-tuf-api-1     | Process SpawnProcess-1:
dev-repository-service-tuf-api-repository-service-tuf-api-1     | Traceback (most recent call last):
dev-repository-service-tuf-api-repository-service-tuf-api-1     |   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
dev-repository-service-tuf-api-repository-service-tuf-api-1     |     self.run()
dev-repository-service-tuf-api-repository-service-tuf-api-1     |   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
dev-repository-service-tuf-api-repository-service-tuf-api-1     |     self._target(*self._args, **self._kwargs)
dev-repository-service-tuf-api-repository-service-tuf-api-1     |   File "/usr/local/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
dev-repository-service-tuf-api-repository-service-tuf-api-1     |     target(sockets=sockets)
dev-repository-service-tuf-api-repository-service-tuf-api-1     |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
dev-repository-service-tuf-api-repository-service-tuf-api-1     |     return asyncio.run(self.serve(sockets=sockets))
dev-repository-service-tuf-api-repository-service-tuf-api-1     |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
dev-repository-service-tuf-api-repository-service-tuf-api-1     |     return loop.run_until_complete(main)
dev-repository-service-tuf-api-repository-service-tuf-api-1     |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
dev-repository-service-tuf-api-repository-service-tuf-api-1     |     return future.result()
dev-repository-service-tuf-api-repository-service-tuf-api-1     |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 67, in serve
dev-repository-service-tuf-api-repository-service-tuf-api-1     |     config.load()
dev-repository-service-tuf-api-repository-service-tuf-api-1     |   File "/usr/local/lib/python3.10/site-packages/uvicorn/config.py", line 474, in load
dev-repository-service-tuf-api-repository-service-tuf-api-1     |     self.loaded_app = import_from_string(self.app)
dev-repository-service-tuf-api-repository-service-tuf-api-1     |   File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
dev-repository-service-tuf-api-repository-service-tuf-api-1     |     module = importlib.import_module(module_str)
dev-repository-service-tuf-api-repository-service-tuf-api-1     |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
dev-repository-service-tuf-api-repository-service-tuf-api-1     |     return _bootstrap._gcd_import(name[level:], package, level)
dev-repository-service-tuf-api-repository-service-tuf-api-1     |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
dev-repository-service-tuf-api-repository-service-tuf-api-1     |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
dev-repository-service-tuf-api-repository-service-tuf-api-1     |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
dev-repository-service-tuf-api-repository-service-tuf-api-1     |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
dev-repository-service-tuf-api-repository-service-tuf-api-1     |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
dev-repository-service-tuf-api-repository-service-tuf-api-1     |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
dev-repository-service-tuf-api-repository-service-tuf-api-1     |   File "/opt/repository-service-tuf-api/./app.py", line 31, in <module>
dev-repository-service-tuf-api-repository-service-tuf-api-1     |     logging.info(f"Bootstrap on this node enabled: {settings.BOOTSTRAP_NODE}")
dev-repository-service-tuf-api-repository-service-tuf-api-1     |   File "/usr/local/lib/python3.10/site-packages/dynaconf/base.py", line 138, in __getattr__
dev-repository-service-tuf-api-repository-service-tuf-api-1     |     value = getattr(self._wrapped, name)
dev-repository-service-tuf-api-repository-service-tuf-api-1     |   File "/usr/local/lib/python3.10/site-packages/dynaconf/base.py", line 300, in __getattribute__
dev-repository-service-tuf-api-repository-service-tuf-api-1     |     return super().__getattribute__(name)
dev-repository-service-tuf-api-repository-service-tuf-api-1     | AttributeError: 'Settings' object has no attribute 'BOOTSTRAP_NODE'
```

### Reproduction steps

1. Remove the variable `RSTUF_BOOTSTRAP_NODE` from docker-compose file
2. make run-dev
3. check the logs
...

### Expected behavior

If the variable is not set the default should be false as describe in the documentation.

**Comment by kairoaraujo** [comment]
Closed by
- #334
