### ISSUE TITLE
Bug: Umapped (`PRE_RUN`) state when task is retrieved to fast after submitting

### ISSUE THREAD

**Issue by kairoaraujo** [repository-service-tuf/repository-service-tuf-api#545]
### What happened?

There is an unmapped state in the RSTUF API, that is, `PRE-RUN.`

I got it while doing a bootstrap locally.

```log
repository-service-tuf-api-repository-service-tuf-api-1     | INFO:     192.168.65.1:56303 - "POST /api/v1/bootstrap/ HTTP/1.1" 202 Accepted
repository-service-tuf-api-repository-service-tuf-api-1     | INFO:     192.168.65.1:56328 - "GET /api/v1/task/?task_id=f95df0db86e94254ba9798502c4f405c HTTP/1.1" 500 Internal Server Error
repository-service-tuf-api-repository-service-tuf-api-1     | ERROR:    Exception in ASGI application
repository-service-tuf-api-repository-service-tuf-api-1     | Traceback (most recent call last):
repository-service-tuf-api-repository-service-tuf-api-1     |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 412, in run_asgi
repository-service-tuf-api-repository-service-tuf-api-1     |     result = await app(  # type: ignore[func-returns-value]
repository-service-tuf-api-repository-service-tuf-api-1     |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
repository-service-tuf-api-repository-service-tuf-api-1     |     return await self.app(scope, receive, send)
repository-service-tuf-api-repository-service-tuf-api-1     |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
repository-service-tuf-api-repository-service-tuf-api-1     |     await super().__call__(scope, receive, send)
repository-service-tuf-api-repository-service-tuf-api-1     |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
repository-service-tuf-api-repository-service-tuf-api-1     |     await self.middleware_stack(scope, receive, send)
repository-service-tuf-api-repository-service-tuf-api-1     |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
repository-service-tuf-api-repository-service-tuf-api-1     |     raise exc
repository-service-tuf-api-repository-service-tuf-api-1     |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
repository-service-tuf-api-repository-service-tuf-api-1     |     await self.app(scope, receive, _send)
repository-service-tuf-api-repository-service-tuf-api-1     |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
repository-service-tuf-api-repository-service-tuf-api-1     |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
repository-service-tuf-api-repository-service-tuf-api-1     |   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
repository-service-tuf-api-repository-service-tuf-api-1     |     raise exc
repository-service-tuf-api-repository-service-tuf-api-1     |   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
repository-service-tuf-api-repository-service-tuf-api-1     |     await app(scope, receive, sender)
repository-service-tuf-api-repository-service-tuf-api-1     |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 758, in __call__
repository-service-tuf-api-repository-service-tuf-api-1     |     await self.middleware_stack(scope, receive, send)
repository-service-tuf-api-repository-service-tuf-api-1     |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 778, in app
repository-service-tuf-api-repository-service-tuf-api-1     |     await route.handle(scope, receive, send)
repository-service-tuf-api-repository-service-tuf-api-1     |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 299, in handle
repository-service-tuf-api-repository-service-tuf-api-1     |     await self.app(scope, receive, send)
repository-service-tuf-api-repository-service-tuf-api-1     |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 79, in app
repository-service-tuf-api-repository-service-tuf-api-1     |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
repository-service-tuf-api-repository-service-tuf-api-1     |   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
repository-service-tuf-api-repository-service-tuf-api-1     |     raise exc
repository-service-tuf-api-repository-service-tuf-api-1     |   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
repository-service-tuf-api-repository-service-tuf-api-1     |     await app(scope, receive, sender)
repository-service-tuf-api-repository-service-tuf-api-1     |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 74, in app
repository-service-tuf-api-repository-service-tuf-api-1     |     response = await func(request)
repository-service-tuf-api-repository-service-tuf-api-1     |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 299, in app
repository-service-tuf-api-repository-service-tuf-api-1     |     raise e
repository-service-tuf-api-repository-service-tuf-api-1     |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 294, in app
repository-service-tuf-api-repository-service-tuf-api-1     |     raw_response = await run_endpoint_function(
repository-service-tuf-api-repository-service-tuf-api-1     |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
repository-service-tuf-api-repository-service-tuf-api-1     |     return await run_in_threadpool(dependant.call, **values)
repository-service-tuf-api-repository-service-tuf-api-1     |   File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
repository-service-tuf-api-repository-service-tuf-api-1     |     return await anyio.to_thread.run_sync(func, *args)
repository-service-tuf-api-repository-service-tuf-api-1     |   File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
repository-service-tuf-api-repository-service-tuf-api-1     |     return await get_async_backend().run_sync_in_worker_thread(
repository-service-tuf-api-repository-service-tuf-api-1     |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
repository-service-tuf-api-repository-service-tuf-api-1     |     return await future
repository-service-tuf-api-repository-service-tuf-api-1     |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
repository-service-tuf-api-repository-service-tuf-api-1     |     result = context.run(func, *args)
repository-service-tuf-api-repository-service-tuf-api-1     |   File "/opt/repository-service-tuf-api/repository_service_tuf_api/api/tasks.py", line 25, in get
repository-service-tuf-api-repository-service-tuf-api-1     |     return tasks.get(params.task_id)
repository-service-tuf-api-repository-service-tuf-api-1     |   File "/opt/repository-service-tuf-api/repository_service_tuf_api/tasks.py", line 153, in get
repository-service-tuf-api-repository-service-tuf-api-1     |     data=TasksData(task_id=task_id, state=task_state, result=task_result),
repository-service-tuf-api-repository-service-tuf-api-1     |   File "/usr/local/lib/python3.10/site-packages/pydantic/main.py", line 171, in __init__
repository-service-tuf-api-repository-service-tuf-api-1     |     self.__pydantic_validator__.validate_python(data, self_instance=self)
repository-service-tuf-api-repository-service-tuf-api-1     | pydantic_core._pydantic_core.ValidationError: 1 validation error for TasksData
repository-service-tuf-api-repository-service-tuf-api-1     | state
repository-service-tuf-api-repository-service-tuf-api-1     |   Input should be 'PENDING', 'RECEIVED', 'STARTED', 'SUCCESS', 'FAILURE', 'REVOKED', 'REJECTED', 'RETRY', 'IGNORED', 'ERRORED' or 'RUNNING' [type=enum, input_value='PRE_RUN', input_type=str]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by muhahahmad68** [comment]
Hello, @kairoaraujo 
Gone through the issue, i don't seem to understand fully what the problem is.
Does it imply that PRE_RUN has to be a state on its own as well? Just like PENDING RUNNING are states

**Comment by MVrachev** [comment]
Sorry @muhahahmad68 I already proposed a pr fixing this #592
